default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: stoic_development

test:
  <<: *default
  database: stoic_test

production:
  <<: *default
  database: stoic_production
  username: stoic
  password: <%= ENV['STOIC_DATABASE_PASSWORD'] %>
